name: emoji_alert
description: Flutter Emoji Alert, give you the possiblity to create beautiful yet simple alert dialogs and bottom sheet modals
version: 1.0.0
homepage: https://github.com/koukibadr/Emoji_Alert

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/happy.png
    - assets/images/angry.png
    - assets/images/confused.png
    - assets/images/cool.png
    - assets/images/joyful.png
    - assets/images/laughing.png
    - assets/images/sad.png
    - assets/images/scared.png
    - assets/images/shocked.png
    - assets/images/smile.png
    - assets/images/wink.png