import 'constants.dart';

enum EMOJI_TYPE {
  ANGRY,
  CONFUSED,
  COOL,
  HAPPY,
  JOYFUL,
  LAUGHING,
  SAD,
  SCARED,
  SHOCKED,
  SMILE,
  WINK
}

const Map<EMOJI_TYPE, String> EMOJIS = {
  EMOJI_TYPE.ANGRY: EMOJI_ANGRY,
  EMOJI_TYPE.CONFUSED: EMOJI_CONFUSED,
  EMOJI_TYPE.COOL: EMOJI_COOL,
  EMOJI_TYPE.JOYFUL: EMOJI_JOYFUL,
  EMOJI_TYPE.HAPPY: EMOJI_HAPPY,
  EMOJI_TYPE.LAUGHING: EMOJI_LAUGHING,
  EMOJI_TYPE.SAD: EMOJI_SAD,
  EMOJI_TYPE.SCARED: EMOJI_SCARED,
  EMOJI_TYPE.SHOCKED: EMOJI_SHOCKED,
  EMOJI_TYPE.SMILE: EMOJI_SMILE,
  EMOJI_TYPE.WINK: EMOJI_WINK
};

enum CORNER_RADIUS_TYPES { BOTTOM_ONLY, TOP_ONLY, ALL_CORNERS, NONE }

enum ANIMATION_TYPE { NONE, FADEIN, TRANSITION, ROTATION }
